image: "credativ/debian-build:stretch"

variables:
  DEPLOY_SSH_USER: "ansible"
  DEPLOY_SSH_PORT: "22"

stages:
  - docbuild
  - build
  - publish
  # - test
  - deploy

### build ###

docbuild:docs:
  stage: docbuild
  image: "tianon/latex"
  script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends make sphinx-common python3-sphinx python3-recommonmark python3-sphinx-rtd-theme
    - make docs
  artifacts:
    paths:
      - doc/_build/html

build:stretch: &build
  stage: build
  script:
    - apt-get update -qq
    - apt-get -y --no-install-recommends build-dep ./
    - apt-get -y --no-install-recommends install devscripts git
    - ci/rebuild.sh deb9
    - make deb
    - mkdir -p debs
    - mv ../*.* debs
  artifacts:
    expire_in: 2 weeks
    paths:
      - debs/*
      - lintian.log

build:stretch-release:
  <<: *build
  script:
    - apt-get -y --no-install-recommends build-dep ./
    - apt-get -y --no-install-recommends install devscripts git
    - ci/rebuild.sh deb9 release
    - make deb
    - mkdir -p debs
    - mv ../*.* debs
  when: manual

build:bionic: &build_bionic
  <<: *build
  # 2018-04-25: bionic image hanging on configuring tzdata, use stretch for now
  #image: "ubuntu:bionic"
  script:
    - apt-get update -qq
    - apt-get -y --no-install-recommends build-dep ./
    - apt-get -y --no-install-recommends install devscripts git
    - ci/rebuild.sh ubuntu18.04
    - make deb
    - mkdir -p debs
    - mv ../*.* debs

build:bionic-release:
  <<: *build_bionic
  script:
    - apt-get update -qq
    - apt-get -y --no-install-recommends build-dep ./
    - apt-get -y --no-install-recommends install devscripts git
    - ci/rebuild.sh ubuntu18.04 release
    - make deb
    - mkdir -p debs
    - mv ../*.* debs
  when: manual

build:centos7: &build_centos7
  image: "centos:centos7"
  stage: build
  dependencies:
    - docbuild:docs
  script:
    - yum install -y rpm-build yum-utils git make
    - yum-builddep -y rpm/elephant-shed.spec
    - make rpmbuild PACKAGE_RELEASE=1~$(git log --oneline | wc -l)
  artifacts:
    expire_in: 2 weeks
    paths:
      - rpm/RPMS/*/*
      - rpm/SRPMS/*

build:centos7-release:
  <<: *build_centos7
  script:
    - yum install -y rpm-build yum-utils git make
    - yum-builddep -y rpm/elephant-shed.spec
    - make rpmbuild
  when: manual

### publish ###

publish:stretch: &publish
  tags:
    - aptly
  stage: publish
  dependencies:
    - build:stretch
  script:
    - aptly repo add stretch-test debs/*.dsc debs/*.deb
    - aptly publish update stretch-test
    - sync_packages.sh
  only:
    - master

publish:stretch-release:
  <<: *publish
  dependencies:
    - build:stretch-release
  script:
    - aptly repo add stretch-stable debs/*.dsc debs/*.deb
    - aptly publish update stretch-stable
    - sync_packages.sh
  when: manual

publish:bionic: &publish_bionic
  <<: *publish
  dependencies:
    - build:bionic
  script:
    - aptly repo add bionic-test debs/*.dsc debs/*.deb
    - aptly publish update bionic-test
    - sync_packages.sh

publish:bionic-release:
  <<: *publish_bionic
  dependencies:
    - build:bionic-release
  script:
    - aptly repo add bionic-stable debs/*.dsc debs/*.deb
    - aptly publish update bionic-stable
    - sync_packages.sh
  when: manual

publish:centos7:
  <<: *publish
  dependencies:
    - build:centos7
  script:
    - rpm --addsign rpm/RPMS/noarch/*.rpm rpm/SRPMS/*.rpm
    - cp rpm/RPMS/noarch/*.rpm /home/debian/postgresql/yum/el7-test/noarch
    - cp rpm/SRPMS/*.rpm /home/debian/postgresql/yum/el7-test/src
    - cd /home/debian; make yum-test

publish:centos7-release:
  <<: *publish
  dependencies:
    - build:centos7-release
  script:
    - rpm --addsign rpm/RPMS/noarch/*.rpm rpm/SRPMS/*.rpm
    - cp rpm/RPMS/noarch/*.rpm /home/debian/postgresql/yum/el7/noarch
    - cp rpm/SRPMS/*.rpm /home/debian/postgresql/yum/el7/src
    - cd /home/debian; make yum-release
  when: manual

### deploy ###

deploy:x86:
  stage: deploy
  dependencies:
    - publish:stretch
  script:
    - sudo apt-get update -qq
    - sudo apt-get install -y ansible
    - cd vagrant
    - echo "$DEPLOY_X86_SSH_KEY" > id_file
    - chmod 0600 id_file
    - echo "[test]" > inventory
    - echo "$DEPLOY_X86_NAME ansible_ssh_host=${DEPLOY_X86_IP} ansible_ssh_port=${DEPLOY_SSH_PORT} ansible_ssh_user=${DEPLOY_SSH_USER} ansible_ssh_private_key_file=id_file" >> inventory
    # We can't provide this envirionment variable throught "variables" for some reason.
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i inventory elephant-shed.yml
  only:
    - master
  environment:
    name: elephant-shed
    url: https://elephant-shed.dev.credativ.lan

deploy:ppc64el:
  stage: deploy
  dependencies:
    - publish:stretch
  script:
    - sudo apt-get update -qq
    - sudo apt-get install -y ansible
    - cd vagrant
    - echo "$DEPLOY_PPC64EL_SSH_KEY" > id_file
    - chmod 0600 id_file
    - echo "[test]" > inventory
    - echo "$DEPLOY_PPC64EL_NAME ansible_ssh_host=${DEPLOY_PPC64EL_IP} ansible_ssh_port=${DEPLOY_SSH_PORT} ansible_ssh_user=${DEPLOY_SSH_USER} ansible_ssh_private_key_file=id_file" >> inventory
    # We can't provide this envirionment variable throught "variables" for some reason.
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i inventory elephant-shed.yml
  only:
    - master
  environment:
    name: elephant-shed-ppc64el
    url: https://elephant-shed-ppc64el.dev.credativ.lan

deploy:bionic-x86:
  stage: deploy
  dependencies:
    - publish:bionic
  script:
    - sudo apt-get update -qq
    - sudo apt-get install -y ansible
    - cd vagrant
    - echo "$DEPLOY_X86_SSH_KEY" > id_file
    - chmod 0600 id_file
    - echo "[test]" > inventory
    - echo "$DEPLOY_X86_BIONIC_NAME ansible_ssh_host=${DEPLOY_X86_BIONIC_IP} ansible_ssh_port=${DEPLOY_SSH_PORT} ansible_ssh_user=${DEPLOY_SSH_USER} ansible_ssh_private_key_file=id_file" >> inventory
    # We can't provide this envirionment variable throught "variables" for some reason.
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i inventory elephant-shed.yml
  only:
    - master
  environment:
    name: elephant-shed-bionic
    url: https://elephant-shed-bionic.dev.credativ.lan

deploy:centos7-x86:
  tags:
    - centos7-x86
  stage: deploy
  dependencies:
    - build:centos7
  script:
    - 'test -f /etc/yum.repos.d/credativ-test.repo || sudo yum install https://packages.credativ.com/public/postgresql/yum/credativ-test-repo.rpm'
    - sudo yum clean expire-cache
    - sudo yum update -y
    - sudo yum install -y elephant-shed
  only:
    - master
  environment:
    name: elephant-shed-centos7
    url: https://elephant-shed-centos7.dev.credativ.lan
